### ISSUE TITLE
AES only supported by Android API 23+

### ISSUE THREAD

**Issue by erlangp** [HussainDerry/secure-preferences#5]
AES only supported by Android API 23+
https://developer.android.com/training/articles/keystore.html

**Comment by HussainDerry** [comment]
Thanks alot! totally slipped my mind, I'll be solving it asap

**Comment by HussainDerry** [comment]
The link you provided is for the Android keystore system.

Here is the link you should be checking out: 
https://developer.android.com/guide/topics/security/cryptography#SupportedCipher
Both **AES** and **DESede** with all their modes are supported since API 1+, except the **GCM** for **AES** which is supported since API 10+

**Comment by erlangp** [comment]
owh thanks sir :+1:
